### ISSUE TITLE
Question for the Cambridge Landmarks Dataset

### ISSUE THREAD

**Issue by EricLee0224** [yolish/multi-scene-pose-transformer#5]
Hi, thank you for sharing the source code! I would like to check with you if the dataset is available for download, I have not been able to open the Cambridge Landmarks dataset's URL.  TwT

**Comment by yolish** [comment]
Hi, it indeed seems that this dataset is no longer available for download. You will need to contact the authors directly to get access, since it is not mine (IP-wise) to publicly share... The dataset was created by the authors of PoseNet (ICCV2015). If you still having problems with getting access through the authors, please contact me via email and I'll see if I can help.
